# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8685f655600f1f0da4e6102b369cd9d972f5e18871ced28ae344e43753071450e8e921646fa0ff843d2d619ce3bdad503f5a8095267440cbf5d0ea3a5b0e4d55

test:
  secret_key_base: 62b78536f692bb9b3f978a11f004f95cbb8bd3b06f66928a0a46eff6e7e9a6365c7211ea24689f45300dfe2738df90b9b23584f50e5527cc48e80c09d6c3fb78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
